platform :ios, '6.0'

target 'Aspose.Storage_Cloud_SDK_For_Objective_C' do
	pod 'AFNetworking', '~> 2.0'
	pod 'JSONModel', '~> 1.1'
	pod 'ISO8601', '~> 0.3'
end

target 'Aspose.Storage_Cloud_SDK_For_Objective_CTests' do
	pod 'JSONModel', '~> 1.1'
end